# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
